#!/bin/sh
set -e

# Ensure /code/web directory exists, preventing Apache from crashing.
mkdir -p /code/web

# If it's set, ensure $WEB_PATH starts with a slash.
WEB_PATH=$(echo ${WEB_PATH} | sed 's#^\([^/]\)#/\1#')

# Unset $WEB_PATH if it's just a slash. Otherwise Apache does weird things.
if [ "${WEB_PATH}" == "/" ]; then
  unset WEB_PATH
fi

# If $PUBLIC_DIR is set, symlink it to /shared/public and is owned by www-data.
if [ "${PUBLIC_DIR}" ]; then
  mkdir -p /shared/public
  # Only create symlink if it does not already exist.
  if [ ! -h /code/${PUBLIC_DIR} ]; then
    ln -sf /shared/public /code/${PUBLIC_DIR}
  fi
  chown -R 33:0 /shared/public
fi

# If $PRIVATE_DIR is set, ensure it exists and is owned by www-data.
if [ "${PRIVATE_DIR}" ]; then
  mkdir -p ${PRIVATE_DIR}
  chown -R 33:0 ${PRIVATE_DIR}
fi

exec apache2 -D FOREGROUND
