#!/bin/sh
set -e

# Ensure /code/web directory exists, preventing Apache from crashing.
mkdir -p /code/web

# If it's set, ensure $WEB_PATH starts with a slash.
WEB_PATH=$(echo ${WEB_PATH} | sed 's#^\([^/]\)#/\1#')

# Unset $WEB_PATH if it's just a slash. Otherwise Apache does weird things.
if [ "${WEB_PATH}" == "/" ]; then
  unset WEB_PATH
fi

exec apache2 -D FOREGROUND
